export const products = {
    bras_classic: {
        id: 1,
        title: "Classic Bras",
        routeName: 'bras_classic',
        items: [
            {
                id: 1,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic plumetis bra',
                description: 'Classic bra with glitter plumetis effect and double straps. A delicate and feminine wardrobe must-have.',
                category: "Bras, classic",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 2,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 3,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 4,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 5,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 6,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "23.00"
            },
            {
                id: 7,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Contrast lace classic bra',
                description: 'Classic bra with contrast floral lace. Option to cross straps at the back. You are going to fall in love with this must-have.',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 8,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral mesh bra',
                description: 'Classic bra in printed mesh with floral lace at the cups. Contrast straps, wider at the back. Sexy and on-trend!',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 9,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "26.00"
            },
            {
                id: 10,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "23.00"
            },
            {
                id: 11,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "24.00"
            },
            {
                id: 12,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 13,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic bra with floral lace and bow detail on the neckline. Super sexy and feminine.',
                category: "Bras, classic",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 14,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic bra with floral lace and bow detail on the neckline. Super sexy and feminine.',
                category: "Bras, classic",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 15,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic bra with floral lace and bow detail on the neckline. Super sexy and feminine.',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 16,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "24.00"
            },
            {
                id: 17,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic microfibre bra',
                description: 'Classic plain bra in satin effect microfibre. Crossed over between the cups to avoid any marks. Double straps with gold details and the "Mamselles" logo on one side. Elegance and comfort in one bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "33.00"
            },
            {
                id: 18,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic microfibre bra',
                description: 'Classic plain bra in satin effect microfibre. Crossed over between the cups to avoid any marks. Double straps with gold details and the "Mamselles" logo on one side. Elegance and comfort in one bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 19,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic microfibre bra',
                description: 'Classic plain bra in satin effect microfibre. Crossed over between the cups to avoid any marks. Double straps with gold details and the "Mamselles" logo on one side. Elegance and comfort in one bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "34.00"
            },
            {
                id: 20,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic modal bra',
                description: 'The underwire in the BEAUTIFUL bra subtly lifts and centres the bust in a flattering, super sexy style. Classic modal and microfibre bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "26.00"
            },
        ]
    },
    bras_pushup: {
        id: 1,
        title: "Pushup Bras",
        routeName: 'bras_pushup',
        items: [
            {
                id: 21,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. A delicate and feminine wardrobe must-have.',
                category: "Bras, push-up",
                type: "Bras",
                price: "26.00"
            },
            {
                id: 22,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. A delicate and feminine wardrobe must-have.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 23,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. A delicate and feminine wardrobe must-have.',
                category: "Bras, push-up",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 24,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. A delicate and feminine wardrobe must-have.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 25,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra with strappy back. Add a sexy splash of colour to your lingerie look.',
                category: "Bras, push-up",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 26,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Floral lace push-up bra. Gorgeous cut out detail with strappy front and wide straps. The perfect bra for both special occasions and everyday wear.',
                category: "Bras, push-up",
                type: "Bras",
                price: "33.00"
            },
            {
                id: 27,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Plumetis push-up bra',
                description: 'Plumetis push up bra with bow detail at the front and lace at the back. Feminine, comfortable, and sexy!',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 28,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Long-sleeved push-up crop top',
                description: 'Long-sleeved bra top with lace and tulle. Cut out detail at the back. A super feminine and sexy design.',
                category: "Bras, push-up",
                type: "Bras",
                price: "38.00"
            },
            {
                id: 29,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Push-up bra with lace flowers',
                description: 'Push up bra in floral lace with bow detail at the cleavage. Super sensual and feminine.',
                category: "Bras, push-up",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 30,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. Gorgeous cut out detail with strappy front and wide satin straps. The perfect bra for both special occasions and everyday wear.',
                category: "Bras, push-up",
                type: "Bras",
                price: "32.00"
            },
            {
                id: 31,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Floral lace push up bra with crossed straps and lace inlay detail at the back. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, push-up",
                type: "Bras",
                price: "26.00"
            },
            {
                id: 32,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Floral lace push up bra with crossed straps and lace inlay detail at the back. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, push-up",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 33,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Strappy lace push-up bra',
                description: 'Floral lace push-up bra with thin straps on the cups. Bow detail. Super sexy and feminine.',
                category: "Bras, push-up",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 34,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Strappy lace push-up bra',
                description: 'Floral lace push-up bra with thin straps on the cups. Bow detail. Super sexy and feminine.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 35,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace and tulle push-up bra',
                description: 'Push up bra in with floral lace and tulle details, and a bow at the cleavage. A feminine classic that will be your favourite.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 36,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace and tulle push-up bra',
                description: 'Push up bra in with floral lace and tulle details, and a bow at the cleavage. A feminine classic that will be your favourite.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 37,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle detail push-up bra',
                description: 'Push-up bra with neckline detail and microfibre and tulle fabric sides. Show it off to add a sexy and elegant touch to your look.',
                category: "Bras, push-up",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 38,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Push up bra with floral lace. Gorgeous cut out detail with satin straps at the front and back, and wide lace straps. The perfect bra for both special occasions and everyday wear.',
                category: "Bras, push-up",
                type: "Bras",
                price: "33.00"
            },
            {
                id: 39,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Push up bra with floral lace. Gorgeous cut out detail with satin straps at the front and back, and wide lace straps. The perfect bra for both special occasions and everyday wear.',
                category: "Bras, push-up",
                type: "Bras",
                price: "33.00"
            },
            {
                id: 40,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Strappy lace push-up bralette',
                description: 'Floral lace push-up bralette with crossover straps at the front and cups, and cut out details at the back. A super feminine and sensual design.',
                category: "Bras, push-up",
                type: "Bras",
                price: "33.00"
            },
        ]
    },
    bras_bralettes: {
        id: 3,
        title: "Bralettes",
        routeName: 'bras_bralettes',
        items: [
            {
                id: 41,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace Bralette',
                description: 'Floral lace bralette with clasps at the back. Bow on the front. A super feminine and sensual design.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 42,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace triangle bralette',
                description: 'Lace triangle bralette without underwire or padding. Add a splash of colour to your lingerie look. Dare to show it off?',
                category: "Bras, bralettes",
                type: "Bras",
                price: "26.00"
            },
            {
                id: 43,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Flowery lace bralette',
                description: 'Flowery lace halter bralette with thin strap detail on the neckline. A super sexy model and full of details that will conquer you.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 44,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace bralette',
                description: 'Halter-neck floral lace bralette. A super sexy design, full of details you will love.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 45,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Halter flowery lace bralette',
                description: 'Halter flowery lace bralette. Olympic back. A super sexy model and full of details that will conquer you.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "30.00"
            },
        ]
    }
}