export const products = {
    bras_classic: {
        id: 1,
        title: "Classic Bras",
        routeName: 'bras_classic',
        items: [
            {
                id: 1,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic plumetis bra',
                description: 'Classic bra with glitter plumetis effect and double straps. A delicate and feminine wardrobe must-have.',
                category: "Bras, classic",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 2,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 3,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 4,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 5,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 6,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "23.00"
            },
            {
                id: 7,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Contrast lace classic bra',
                description: 'Classic bra with contrast floral lace. Option to cross straps at the back. You are going to fall in love with this must-have.',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 8,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral mesh bra',
                description: 'Classic bra in printed mesh with floral lace at the cups. Contrast straps, wider at the back. Sexy and on-trend!',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 9,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "26.00"
            },
            {
                id: 10,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "23.00"
            },
            {
                id: 11,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "24.00"
            },
            {
                id: 12,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 13,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic bra with floral lace and bow detail on the neckline. Super sexy and feminine.',
                category: "Bras, classic",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 14,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic bra with floral lace and bow detail on the neckline. Super sexy and feminine.',
                category: "Bras, classic",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 15,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic bra with floral lace and bow detail on the neckline. Super sexy and feminine.',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 16,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "24.00"
            },
            {
                id: 17,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic microfibre bra',
                description: 'Classic plain bra in satin effect microfibre. Crossed over between the cups to avoid any marks. Double straps with gold details and the "Mamselles" logo on one side. Elegance and comfort in one bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "33.00"
            },
            {
                id: 18,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic microfibre bra',
                description: 'Classic plain bra in satin effect microfibre. Crossed over between the cups to avoid any marks. Double straps with gold details and the "Mamselles" logo on one side. Elegance and comfort in one bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 19,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic microfibre bra',
                description: 'Classic plain bra in satin effect microfibre. Crossed over between the cups to avoid any marks. Double straps with gold details and the "Mamselles" logo on one side. Elegance and comfort in one bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "34.00"
            },
            {
                id: 20,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic modal bra',
                description: 'The underwire in the BEAUTIFUL bra subtly lifts and centres the bust in a flattering, super sexy style. Classic modal and microfibre bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "26.00"
            },
        ]
    },
    bras_pushup: {
        id: 1,
        title: "Pushup Bras",
        routeName: 'bras_pushup',
        items: [
            {
                id: 21,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. A delicate and feminine wardrobe must-have.',
                category: "Bras, push-up",
                type: "Bras",
                price: "26.00"
            },
            {
                id: 22,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. A delicate and feminine wardrobe must-have.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 23,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. A delicate and feminine wardrobe must-have.',
                category: "Bras, push-up",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 24,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. A delicate and feminine wardrobe must-have.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 25,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra with strappy back. Add a sexy splash of colour to your lingerie look.',
                category: "Bras, push-up",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 26,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Floral lace push-up bra. Gorgeous cut out detail with strappy front and wide straps. The perfect bra for both special occasions and everyday wear.',
                category: "Bras, push-up",
                type: "Bras",
                price: "33.00"
            },
            {
                id: 27,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Plumetis push-up bra',
                description: 'Plumetis push up bra with bow detail at the front and lace at the back. Feminine, comfortable, and sexy!',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 28,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Long-sleeved push-up crop top',
                description: 'Long-sleeved bra top with lace and tulle. Cut out detail at the back. A super feminine and sexy design.',
                category: "Bras, push-up",
                type: "Bras",
                price: "38.00"
            },
            {
                id: 29,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Push-up bra with lace flowers',
                description: 'Push up bra in floral lace with bow detail at the cleavage. Super sensual and feminine.',
                category: "Bras, push-up",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 30,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace push-up bra',
                description: 'Lace push-up bra. Gorgeous cut out detail with strappy front and wide satin straps. The perfect bra for both special occasions and everyday wear.',
                category: "Bras, push-up",
                type: "Bras",
                price: "32.00"
            },
            {
                id: 31,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Floral lace push up bra with crossed straps and lace inlay detail at the back. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, push-up",
                type: "Bras",
                price: "26.00"
            },
            {
                id: 32,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Floral lace push up bra with crossed straps and lace inlay detail at the back. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, push-up",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 33,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Strappy lace push-up bra',
                description: 'Floral lace push-up bra with thin straps on the cups. Bow detail. Super sexy and feminine.',
                category: "Bras, push-up",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 34,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Strappy lace push-up bra',
                description: 'Floral lace push-up bra with thin straps on the cups. Bow detail. Super sexy and feminine.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 35,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace and tulle push-up bra',
                description: 'Push up bra in with floral lace and tulle details, and a bow at the cleavage. A feminine classic that will be your favourite.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 36,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace and tulle push-up bra',
                description: 'Push up bra in with floral lace and tulle details, and a bow at the cleavage. A feminine classic that will be your favourite.',
                category: "Bras, push-up",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 37,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle detail push-up bra',
                description: 'Push-up bra with neckline detail and microfibre and tulle fabric sides. Show it off to add a sexy and elegant touch to your look.',
                category: "Bras, push-up",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 38,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Push up bra with floral lace. Gorgeous cut out detail with satin straps at the front and back, and wide lace straps. The perfect bra for both special occasions and everyday wear.',
                category: "Bras, push-up",
                type: "Bras",
                price: "33.00"
            },
            {
                id: 39,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace push-up bra',
                description: 'Push up bra with floral lace. Gorgeous cut out detail with satin straps at the front and back, and wide lace straps. The perfect bra for both special occasions and everyday wear.',
                category: "Bras, push-up",
                type: "Bras",
                price: "33.00"
            },
            {
                id: 40,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Strappy lace push-up bralette',
                description: 'Floral lace push-up bralette with crossover straps at the front and cups, and cut out details at the back. A super feminine and sensual design.',
                category: "Bras, push-up",
                type: "Bras",
                price: "33.00"
            },
        ]
    },
    bras_bralettes: {
        id: 3,
        title: "Bralettes",
        routeName: 'bras_bralettes',
        items: [
            {
                id: 41,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace Bralette',
                description: 'Floral lace bralette with clasps at the back. Bow on the front. A super feminine and sensual design.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 42,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace triangle bralette',
                description: 'Lace triangle bralette without underwire or padding. Add a splash of colour to your lingerie look. Dare to show it off?',
                category: "Bras, bralettes",
                type: "Bras",
                price: "26.00"
            },
            {
                id: 43,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Flowery lace bralette',
                description: 'Flowery lace halter bralette with thin strap detail on the neckline. A super sexy model and full of details that will conquer you.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 44,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace bralette',
                description: 'Halter-neck floral lace bralette. A super sexy design, full of details you will love.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 45,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Halter flowery lace bralette',
                description: 'Halter flowery lace bralette. Olympic back. A super sexy model and full of details that will conquer you.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 46,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Flowery lace bralette',
                description: 'Flowery lace halter bralette with thin strap detail on the neckline. A super sexy model and full of details that will conquer you.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 47,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Strappy lace push-up bralette',
                description: 'Floral lace push-up bralette with crossover straps at the front and cups, and cut out details at the back. A super feminine and sensual design.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "32.00"
            },
            {
                id: 48,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace bralette',
                description: 'Lace halter-neck bralette with double straps, fastens at front with clasps. A super sexy design, full of details you will love.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 49,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace triangle bralette',
                description: 'Lace triangle bralette without underwire or padding. Add a splash of colour to your lingerie look. Dare to show it off?',
                category: "Bras, bralettes",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 50,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Long-sleeved crop top',
                description: 'Long-sleeved bra top. Lace and plumetis design with front fastening and opening detail.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "39.00"
            },
            {
                id: 51,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace triangle bralette',
                description: 'Floral lace triangle bralette. Fixed cups, clasps at the back, and adjustable straps. A super sexy design, full of details you will love.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 52,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Halter floweryl lace bralette',
                description: 'Halter flowery lace bralette. A super sexy model and full of details that will conquer you.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 53,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace bralette with fixed cups',
                description: 'Floral lace bralette. Fixed cups, and straps that can be crossed over at the back. A super sexy design, full of details you willl love.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 54,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Corset style bra top',
                description: 'Corset style bra top. Satin design with lace and wide straps. A super feminine and sexy design.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "34.00"
            },
            {
                id: 55,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Corset style bra top',
                description: 'Corset style bra top. Satin design with lace and wide straps. A super feminine and sexy design.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "34.00"
            },
            {
                id: 56,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace bralette',
                description: 'Lace halter-neck bralette with double straps, fastens at front with clasps. A super sexy design, full of details you will love.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 57,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace bralette',
                description: 'Lace halter-neck bralette with double straps, fastens at front with clasps. A super sexy design, full of details you will love.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 58,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Flowery lace and mesh bralette',
                description: 'Flowery lace bralette with mesh at the neckline and back and open detail on the back.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 59,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Long-sleeved push-up crop top',
                description: 'Long-sleeved bra top with lace and tulle. Cut out detail at the back. A super feminine and sexy design.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "36.00"
            },
            {
                id: 60,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Halter flowery lace bralette',
                description: 'Halter flowery lace bralette. Olympic back. A super sexy model and full of details that will conquer you.',
                category: "Bras, bralettes",
                type: "Bras",
                price: "26.00"
            },
        ]
    },
    bras_triangle: {
        id: 4,
        title: "Triangle",
        routeName: 'bras_triangle',
        items: [
            {
                id: 61,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Plumetis triangle bra',
                description: 'Plumetis triangle bra with lace details and bow at the front. Crossover straps design. A delicate and feminine wardrobe must-have',
                category: "Bras, triangle",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 62,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace triangle bra',
                description: 'Triangle bra with lace details. Double straps design. A delicate and feminine wardrobe must-have.',
                category: "Bras, triangle",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 63,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Guipure halter-neck bra',
                description: 'Halter-neck, half padded, the INTUITIVE bra with soft lace accentuates your sensual side. A wardrobe must.',
                category: "Bras, triangle",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 64,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Halter-neck triangle bra',
                description: 'Halter-neck triangle bra with glitter plumetis effect.',
                category: "Bras, triangle",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 65,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Plumetis triangle bra',
                description: 'Plumetis triangle bra with lace details and bow at the front. Crossover straps design. A delicate and feminine wardrobe must-have',
                category: "Bras, triangle",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 66,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Halter-neck triangle bra',
                description: 'Halter-neck triangle bra with glitter plumetis effect.',
                category: "Bras, triangle",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 67,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Triangular lace bra with straps',
                description: 'Floral lace triangular bra with thin straps on the cups. Metallic piping detail. Super sexy and feminine.',
                category: "Bras, triangle",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 68,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Triangular lace bra with straps',
                description: 'Floral lace triangular bra with thin straps on the cups. Metallic piping detail. Super sexy and feminine.',
                category: "Bras, triangle",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 69,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Triangular lace bra with straps',
                description: 'Floral lace triangular bra with thin straps on the cups. Metallic piping detail. Super sexy and feminine.',
                category: "Bras, triangle",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 70,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Triangular lace bra',
                description: 'Triangular bra with floral lace details. A delicate, feminine option to highlight the natural shape of your chest.',
                category: "Bras, triangle",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 71,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace abd tulle halter bra',
                description: 'Lace halter bra with tulle details and bow on the front. Sensuality and femininity in a single bra.',
                category: "Bras, triangle",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 72,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Triangular lace bra',
                description: 'Triangular bra with floral lace details. A delicate, feminine option to highlight the natural shape of your chest.',
                category: "Bras, triangle",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 73,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Satin effect triangle bra with lace',
                description: 'Satin effect triangle bra with contrast floral lace trim. The perfect bra for extra special occasions.',
                category: "Bras, triangle",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 74,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Triangle bra with tulle detail',
                description: 'Moulded triangle bar without underwire, with neckline detail and microfibre and tulle fabric sides. Show it off to add a sexy and elegant touch to your look.',
                category: "Bras, triangle",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 75,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Triangular lace bra with straps',
                description: 'Lace triangle bra with satin effect straps at the cups. A fresh and sensual design.',
                category: "Bras, triangle",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 76,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Smooth cotton triangular halter',
                description: 'Smooth cotton triangular halter bra with floral lace details. An everyday essential.',
                category: "Bras, triangle",
                type: "Bras",
                price: "20.00"
            },
            {
                id: 77,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton triangular bra',
                description: 'Smooth cotton triangle halter bra with floral lace details.',
                category: "Bras, triangle",
                type: "Bras",
                price: "24.00"
            },
            {
                id: 78,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace triangle bra',
                description: 'Wireless support and hold for irresistible style. The LOVELY bra is a firm favourite with our customers. Wear it once and then again, and again, and again…',
                category: "Bras, triangle",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 79,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Modal triangle bra',
                description: 'Wireless support and hold for irresistible style. The LOVELY bra is a firm favourite with our customers. Wear it once and then again, and again, and again…',
                category: "Bras, triangle",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 80,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Satin triangle bra',
                description: 'Satin effect triangle bra with thin straps. A fresh and sensual design.',
                category: "Bras, triangle",
                type: "Bras",
                price: "28.00"
            },
        ]
    },
    panties_classic: {
        id: 5,
        title: "Classic Panties",
        routeName: 'panties_classic',
        items: [
            {
                id: 81,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic plumetis strappy panty',
                description: 'Classic panty with glitter plumetis effect. Gathered design with side strap detail. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "16.00"
            },
            {
                id: 82,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace panty',
                description: 'Classic lace panty. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "17.00"
            },
            {
                id: 83,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic plumetis strappy panty',
                description: 'Classic panty with glitter plumetis effect. Gathered design with side strap detail. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "16.00"
            },
            {
                id: 84,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'High-waisted plumetis panty',
                description: 'Glitter effect plumetis high-waisted panty. With velvet details. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "18.00"
            },
            {
                id: 85,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace panty',
                description: 'Classic lace panty. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "18.00"
            },
            {
                id: 86,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace panty with straps',
                description: 'Classic lace panty with crossover straps at the back. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "18.00"
            },
            {
                id: 87,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace panty',
                description: 'Classic lace panty. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "16.00"
            },
            {
                id: 88,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace high-waisted panty',
                description: 'High-waist panty in floral lace with cut out detail at the back with a small jewel. A super sexy and feminine design.',
                category: "Panties, classic",
                type: "Panties",
                price: "19.00"
            },
            {
                id: 89,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace panty',
                description: 'Classic floral lace panty. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "15.00"
            },
            {
                id: 90,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral mesh panty',
                description: 'Classic panty in floral print mesh. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 91,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace panty',
                description: 'Classic floral lace panty with contrast trim. Slogan detail on the front. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "17.00"
            },
            {
                id: 92,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle and lace high-waist panty',
                description: 'High-waist panty in lace and flocked tulle with microfibre details. Accentuating and flattering, for ultimate comfort.',
                category: "Panties, classic",
                type: "Panties",
                price: "19.00"
            },
            {
                id: 93,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace high-waist panty',
                description: 'High-waist panty in floral lace with cut out detail at the back with small metallic bead. A super sexy and feminine design.',
                category: "Panties, classic",
                type: "Panties",
                price: "19.00"
            },
            {
                id: 94,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace panty',
                description: 'Classic floral lace panty with contrast trim. Slogan detail on the front. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "19.00"
            },
            {
                id: 95,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace strappy panty',
                description: 'Classic lace panty with crossover straps at the back. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "17.00"
            },
            {
                id: 96,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic animal print panty',
                description: 'Classic panty in animal print mesh. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "19.00"
            },
            {
                id: 97,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Gorgeous classic plumetis panty',
                description: 'Gorgeous classic plumetis panty with thin crossover straps at the back. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "19.00"
            },
            {
                id: 98,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral mesh panty',
                description: 'Classic panty in floral print mesh. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 99,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace panty',
                description: 'Classic floral lace panty with contrast trim. Slogan detail on the front. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "16.00"
            },
            {
                id: 99,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace panty',
                description: 'Classic floral lace panty with contrast trim. Slogan detail on the front. Sexy and feminine!',
                category: "Panties, classic",
                type: "Panties",
                price: "16.00"
            },
            {
                id: 100,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace panty',
                description: 'Classic panty with floral lace. Feminine and sexy!',
                category: "Panties, classic",
                type: "Panties",
                price: "15.00"
            },
        ]
    },
    panties_thongs: {
        id: 6,
        title: "Thongs",
        routeName: 'panties_thongs',
        items: [
            {
                id: 101,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace thong',
                description: 'Lace tanga-style panty. Sexy and feminine!',
                category: "Panties, thongs",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 102,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace g-strings',
                description: 'Strappy g-string with contrast lace trim. Sexy and feminine!',
                category: "Panties, thongs",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 103,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace thong',
                description: 'Lace tanga-style panty. Sexy and feminine!',
                category: "Panties, thongs",
                type: "Panties",
                price: "14.00"
            },
            {
                id: 104,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace thong',
                description: 'Lace tanga-style panty. Sexy and feminine!',
                category: "Panties, thongs",
                type: "Panties",
                price: "14.00"
            },
            {
                id: 105,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace g-string',
                description: 'G-string with a thin strap in floral lace. Sexy and feminine!',
                category: "Panties, thongs",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 106,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral mesh tanga',
                description: 'Tanga in floral print mesh. Sexy and on-trend!',
                category: "Panties, thongs",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 107,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace g-string',
                description: 'G-string with floral lace. Sexy and feminine!',
                category: "Panties, thongs",
                type: "Panties",
                price: "12.00"
            },
            {
                id: 108,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace g-string',
                description: 'G-string with lace and small metallic beads detail. Sexy and feminine!',
                category: "Panties, thongs",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 109,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace g-string',
                description: 'G-string with a thin strap in floral lace. Sexy and feminine!',
                category: "Panties, thongs",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 110,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace g-string',
                description: 'G-string with lace. Sexy and feminine!',
                category: "Panties, thongs",
                type: "Panties",
                price: "12.00"
            },
            {
                id: 111,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Flocked tulle and lace thong',
                description: 'Flocked tulle strappy thong with lace details. Feel sexy in your daily life.',
                category: "Panties, thongs",
                type: "Panties",
                price: "12.00"
            },
            {
                id: 112,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace thong',
                description: 'Strappy lace thong. Feel sexy at all times.',
                category: "Panties, thongs",
                type: "Panties",
                price: "14.00"
            },
            {
                id: 113,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace thong',
                description: 'Lace and microfibre thong. Dependable basics.',
                category: "Panties, thongs",
                type: "Panties",
                price: "14.00"
            },
            {
                id: 114,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace thong',
                description: 'Strappy lace thong. Feel sexy at all times.',
                category: "Panties, thongs",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 115,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace thong',
                description: 'Strappy lace thong. Feel sexy at all times.',
                category: "Panties, thongs",
                type: "Panties",
                price: "13.00"
            },
            {
                id: 116,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace details thong',
                description: 'Thong-type panties with floral lace. Delicate and feminine.',
                category: "Panties, thongs",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 117,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace thong',
                description: 'Thong-type panties with floral lace. Delicate and feminine.',
                category: "Panties, thongs",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 118,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace details thong',
                description: 'Thong-type panties with floral lace. Delicate and feminine.',
                category: "Panties, thongs",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 119,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace thong',
                description: 'Thong-type panties with floral lace. Delicate and feminine.',
                category: "Panties, thongs",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 120,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton lace thong',
                description: 'Cotton thong with floral lace details and bow. Comfy and feminine. A basic wardrobe essential.',
                category: "Panties, thongs",
                type: "Panties",
                price: "11.00"
            },
        ]
    },
    panties_culottes: {
        id: 7,
        title: "Culottes",
        routeName: 'panties_culottes',
        items: [
            {
                id: 121,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Plumetis boyshorts',
                description: 'Boyshort in plumetis. Sexy and feminine!',
                category: "Panties, culottes",
                type: "Panties",
                price: "17.00"
            },
            {
                id: 122,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Plumetis boyshorts',
                description: 'Boyshort in plumetis. Sexy and feminine!',
                category: "Panties, culottes",
                type: "Panties",
                price: "17.00"
            },
            {
                id: 123,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Wide brazilian lace panty',
                description: 'Wide Brazilian panty with floral lace and front bow detail. Super sexy and feminine.',
                category: "Panties, culottes",
                type: "Panties",
                price: "18.00"
            },
            {
                id: 124,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Wide brazilian lace panty',
                description: 'Wide Brazilian panty with floral lace and front bow detail. Super sexy and feminine.',
                category: "Panties, culottes",
                type: "Panties",
                price: "18.00"
            },
            {
                id: 125,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace culotte',
                description: 'Floral lace culotte. A super feminine essential - your wardrobe needs this.',
                category: "Panties, culottes",
                type: "Panties",
                price: "14.00"
            },
            {
                id: 126,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace culotte',
                description: 'Floral lace culotte. A super feminine essential - your wardrobe needs this.',
                category: "Panties, culottes",
                type: "Panties",
                price: "14.00"
            },
            {
                id: 127,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton culottes with lace',
                description: 'Cotton culottes with floral lace details. Comfy and feminine. A basic wardrobe essential.',
                category: "Panties, culottes",
                type: "Panties",
                price: "15.00"
            },
            {
                id: 128,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton culottes with lace',
                description: 'Cotton culottes with floral lace details. Comfy and feminine. A basic wardrobe essential.',
                category: "Panties, culottes",
                type: "Panties",
                price: "15.00"
            },
            {
                id: 129,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace boyshorts',
                description: 'Floral lace boyshort. A super feminine essential - your wardrobe needs this.',
                category: "Panties, culottes",
                type: "Panties",
                price: "17.00"
            },
            {
                id: 130,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace boyshorts',
                description: 'Floral lace boyshort. A super feminine essential - your wardrobe needs this.',
                category: "Panties, culottes",
                type: "Panties",
                price: "17.00"
            },
            {
                id: 131,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Brazilian lace culotte',
                description: 'Brazilian-style culotte panty with floral lace details. The perfect panty for your feminine side.',
                category: "Panties, culottes",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 132,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton lace culotte',
                description: 'Cotton culotte-type panties, with print and floral lace in the upper part. A comfortable and feminine essential.',
                category: "Panties, culottes",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 133,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton lace culotte',
                description: 'Cotton culotte-type panties, with print and floral lace in the upper part. A comfortable and feminine essential.',
                category: "Panties, culottes",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 134,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton lace culotte',
                description: 'Cotton culotte-type panties, with print and floral lace in the upper part. A comfortable and feminine essential.',
                category: "Panties, culottes",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 135,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton structural culotte',
                description: 'Cotton culotte-type panties with structural lace on the front sides and bow detail. A comfortable and feminine essential.',
                category: "Panties, culottes",
                type: "Panties",
                price: "14.00"
            },
            {
                id: 136,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton lace culotte',
                description: 'Cotton culotte-type panties, with print and floral lace in the upper part. A comfortable and feminine essential.',
                category: "Panties, culottes",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 137,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Brazilian boyshorts panty',
                description: 'Brazilian style boyshort panty, printed, with floral lace trim. Comfortable and feminine.',
                category: "Panties, culottes",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 138,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton boyshorts panty with lace',
                description: 'Cotton boyshort panty, printed, with floral lace detail at the top. The perfect panty for a super feminine look.',
                category: "Panties, culottes",
                type: "Panties",
                price: "9.00"
            },
            {
                id: 139,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton lace culotte',
                description: 'Cotton culotte-type panties, with print and floral lace in the upper part. A comfortable and feminine essential.',
                category: "Panties, culottes",
                type: "Panties",
                price: "11.00"
            },
            {
                id: 140,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Brazilian lace culottepanty',
                description: 'Cotton culotte-type panties, with print and floral lace in the upper part. A comfortable and feminine essential.',
                category: "Panties, culottes",
                type: "Panties",
                price: "10.00"
            },
        ]
    },
    panties_slimming: {
        id: 8,
        title: "Slimming",
        routeName: 'panties_slimming',
        items: [
            {
                id: 141,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'High waist Shape brief',
                description: 'High waist Shape brief.',
                category: "Panties, slimming",
                type: "Panties",
                price: "22.00"
            },
            {
                id: 142,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'High waist Shape brief',
                description: 'High waist Shape brief.',
                category: "Panties, slimming",
                type: "Panties",
                price: "22.00"
            },
            {
                id: 143,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'High waist Shape brief',
                description: 'High waist Shape brief.',
                category: "Panties, slimming",
                type: "Panties",
                price: "22.00"
            },
            {
                id: 144,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'High waist Shape brief',
                description: 'High waist Shape brief.',
                category: "Panties, slimming",
                type: "Panties",
                price: "22.00"
            },
            {
                id: 145,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Shapewear thong',
                description: 'Sculpting tulle thong with extra reinforcement in the front. From our Shapwear collection that slims and flatters your body in soft and high quality fabrics (LYCRA®). Garments created to bring out the best in you.',
                category: "Panties, slimming",
                type: "Panties",
                price: "24.00"
            },
            {
                id: 146,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle shape panty',
                description: 'This tulle panty shapes your curves for a sleeker, slimmer silhouette. From our shapewear collection that slims and flatters your body in soft and quality fabrics.',
                category: "Panties, slimming",
                type: "Panties",
                price: "22.00"
            },
            {
                id: 147,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle shape panty',
                description: 'This tulle panty shapes your curves for a sleeker, slimmer silhouette. From our shapewear collection that slims and flatters your body in soft and quality fabrics.',
                category: "Panties, slimming",
                type: "Panties",
                price: "29.00"
            },
            {
                id: 148,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Shapewear shorts',
                description: 'Sculpting high-waist shorts with extra reinforcement in the front. From our Shapwear collection that slims and flatters your body in soft and high quality fabrics (LYCRA®). Garments created to bring out the best in you.',
                category: "Panties, slimming",
                type: "Panties",
                price: "30.00"
            },
            {
                id: 149,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle shape panty',
                description: 'This tulle panty shapes your curves for a sleeker, slimmer silhouette. From our shapewear collection that slims and flatters your body in soft and quality fabrics.',
                category: "Panties, slimming",
                type: "Panties",
                price: "29.00"
            },
            {
                id: 150,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle shape panty',
                description: 'High waist Shape brief that sit on the hips. A brand line that slims and flatters your body in soft top quality fabrics. Garments created to bring out the best in you. LYCRA®',
                category: "Panties, slimming",
                type: "Panties",
                price: "25.00"
            },
            {
                id: 151,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle shape shorts',
                description: 'This bodyshape shorts in tulle shape your curves to give a defined silhouette. From our shapewear collection that slims and flatters your body in soft and quality fabrics.',
                category: "Panties, slimming",
                type: "Panties",
                price: "33.00"
            },
            {
                id: 152,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Shapewear thong',
                description: 'Sculpting tulle thong with extra reinforcement in the front. From our Shapwear collection that slims and flatters your body in soft and high quality fabrics (LYCRA®). Garments created to bring out the best in you.',
                category: "Panties, slimming",
                type: "Panties",
                price: "22.00"
            },
            {
                id: 153,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'High-waisted maximum support panties with lace',
                description: 'High-waisted maximum support panties with lace details and waist reinforcement. They enhance and stylise with maximum comfort.',
                category: "Panties, slimming",
                type: "Panties",
                price: "17.00"
            },
            {
                id: 154,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'High-waisted maximum support lace and tulle',
                description: 'High-waisted maximum support microfibre, lace and flocked tulle panties. Waist reinforcement. They enhance and stylise with maximum comfort.',
                category: "Panties, slimming",
                type: "Panties",
                price: "16.00"
            },
            {
                id: 155,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'High-waisted maximum support lace and tulle',
                description: 'High-waisted maximum support microfibre, lace and flocked tulle panties. Waist reinforcement. They enhance and stylise with maximum comfort.',
                category: "Panties, slimming",
                type: "Panties",
                price: "16.00"
            },
        ]
    },
    accessories_tights_and_leggins: {
        id: 9,
        title: "Tights and leggins",
        routeName: 'accessories_tights_and_leggins',
        items: [
            {
                id: 156,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Run resistant tights',
                description: 'Run resistant tights, 20 denier. A must-have to every wardrobe.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "17.00"
            },
            {
                id: 157,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Seamless tights 20 DEN',
                description: 'Seamless tights, 20 denier. A must-have to every wardrobe.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "17.00"
            },
            {
                id: 158,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Seamless tights 20 DEN',
                description: 'Seamless tights, 20 denier. A must-have to every wardrobe.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "20.00"
            },
            {
                id: 159,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Seamless tights 20 DEN',
                description: 'Seamless tights, 20 denier. A must-have to every wardrobe.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "20.00"
            },
            {
                id: 160,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Seamless tights 20 DEN',
                description: 'Seamless tights, 20 denier. A must-have to every wardrobe.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "20.00"
            },
            {
                id: 161,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Seamless tights 20 DEN',
                description: 'Seamless tights, 20 denier. A must-have to every wardrobe.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "20.00"
            },
            {
                id: 162,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Seamless tights 20 DEN',
                description: 'Seamless tights, 20 denier. A must-have to every wardrobe.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "20.00"
            },
            {
                id: 163,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Seamless tights 20 DEN',
                description: 'Seamless tights, 20 denier. A must-have to every wardrobe.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "20.00"
            },
            {
                id: 164,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Seamless tights 20 DEN',
                description: 'Seamless tights, 20 denier. A must-have to every wardrobe.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "20.00"
            },
            {
                id: 165,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Stand up tights',
                description: '20 high denier stand up tights with silicone grip perfect for wearing alone or with suspender belt. Can not be returned or exchanged.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "18.00"
            },
            {
                id: 166,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Stand up tights',
                description: '20 high denier stand up tights with silicone grip perfect for wearing alone or with suspender belt. Can not be returned or exchanged.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "18.00"
            },
            {
                id: 167,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Basic plumetis tights',
                description: 'Basic plumetis tights. The favourite of your legs. Can not be returned or exchanged.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "16.00"
            },
            {
                id: 168,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Basic plumetis tights',
                description: 'Basic plumetis tights. The favourite of your legs. Can not be returned or exchanged.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "16.00"
            },
            {
                id: 169,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Basic plumetis tights',
                description: 'Basic plumetis tights. The favourite of your legs. Can not be returned or exchanged.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "16.00"
            },
            {
                id: 170,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Dots tights',
                description: 'Dots tights. The favourite of your legs. Can not be returned or exchanged.',
                category: "Accessories, tights and leggins",
                type: "Accessories",
                price: "17.00"
            },
        ]
    },
    accessories_bodysuits: {
        id: 10,
        title: "Bodysuits",
        routeName: 'accessories_bodysuits',
        items: [
            {
                id: 171,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle shape body slip',
                description: 'Firm control body. From our shapewear collection that slims and flatters your body in soft and quality fabrics.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "48.00"
            },
            {
                id: 172,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Tulle shape body slip',
                description: 'Firm control body. From our shapewear collection that slims and flatters your body in soft and quality fabrics.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "47.00"
            },
            {
                id: 173,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Cotton and lycra body',
                description: 'Plain cotton and Lycra body with removable cups and floral lace straps. A super feminine essential with gorgeous detailing.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "23.00"
            },
            {
                id: 174,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Floral lace body',
                description: 'Floral lace body with halter neck and underwire. Openings at the front and back. A gorgeous, super sexy design, brimming with details you will love.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "40.00"
            },
            {
                id: 175,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace body with neckline detail',
                description: 'Floral lace and plumetis body. Strappy design with straps at the neckline and front and back cut out details. A gorgeous, feminine design.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "46.00"
            },
            {
                id: 176,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace strappy bodysuit',
                description: 'Lace body with tulle details and thin straps at the cups. Strappy design with a satin band at the waist and opening at the back. A delicate and feminine wardrobe must-have.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "39.00"
            },
            {
                id: 177,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Lace and plumetis strappy body',
                description: 'Body in floral lace and plumetis with thin strappy details at the cups and cut out at the back. Super sexy and feminine.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "40.00"
            },
            {
                id: 178,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'V-neck tulle body',
                description: 'Long-sleeved body in tulle microfibre fabric. Flattering neckline and plunging back. An elegant essential with a sexy touch, to show off on those magical and special nights.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "37.00"
            },
            {
                id: 179,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Strappy body',
                description: 'Plain strappy body. A basic essential for your wardrobe.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "24.00"
            },
            {
                id: 180,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Strappy body',
                description: 'Plain strappy body. A basic essential for your wardrobe.',
                category: "Accessories, bodysuits",
                type: "Accessories",
                price: "24.00"
            },
        ]
    }
}