export const products = {
    bras_classic: {
        id: 1,
        title: "Classic Bras",
        routeName: 'bras_classic',
        items: [
            {
                id: 1,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic plumetis bra',
                description: 'Classic bra with glitter plumetis effect and double straps. A delicate and feminine wardrobe must-have.',
                category: "Bras, classic",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 2,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 3,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 4,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 5,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 6,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic lace bra',
                description: 'Classic lace bra with underwire. Add a subtle hint of colour to your lingerie look.',
                category: "Bras, classic",
                type: "Bras",
                price: "23.00"
            },
            {
                id: 7,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Contrast lace classic bra',
                description: 'Classic bra with contrast floral lace. Option to cross straps at the back. You are going to fall in love with this must-have.',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 8,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral mesh bra',
                description: 'Classic bra in printed mesh with floral lace at the cups. Contrast straps, wider at the back. Sexy and on-trend!',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 9,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "26.00"
            },
            {
                id: 10,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "23.00"
            },
            {
                id: 11,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "24.00"
            },
            {
                id: 12,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "25.00"
            },
            {
                id: 13,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic bra with floral lace and bow detail on the neckline. Super sexy and feminine.',
                category: "Bras, classic",
                type: "Bras",
                price: "28.00"
            },
            {
                id: 14,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic bra with floral lace and bow detail on the neckline. Super sexy and feminine.',
                category: "Bras, classic",
                type: "Bras",
                price: "29.00"
            },
            {
                id: 15,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic bra with floral lace and bow detail on the neckline. Super sexy and feminine.',
                category: "Bras, classic",
                type: "Bras",
                price: "27.00"
            },
            {
                id: 16,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic floral lace bra',
                description: 'Classic floral lace bra with lace inlay on the back of the straps. A delicate and feminine model, a must for your wardrobe.',
                category: "Bras, classic",
                type: "Bras",
                price: "24.00"
            },
            {
                id: 17,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic microfibre bra',
                description: 'Classic plain bra in satin effect microfibre. Crossed over between the cups to avoid any marks. Double straps with gold details and the "Mamselles" logo on one side. Elegance and comfort in one bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "33.00"
            },
            {
                id: 18,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic microfibre bra',
                description: 'Classic plain bra in satin effect microfibre. Crossed over between the cups to avoid any marks. Double straps with gold details and the "Mamselles" logo on one side. Elegance and comfort in one bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "30.00"
            },
            {
                id: 19,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic microfibre bra',
                description: 'Classic plain bra in satin effect microfibre. Crossed over between the cups to avoid any marks. Double straps with gold details and the "Mamselles" logo on one side. Elegance and comfort in one bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "34.00"
            },
            {
                id: 20,
                imgSmall_1: '',
                imgSmall_2: '',
                imgBig_1: '',
                imgBig_2: '',
                title: 'Classic modal bra',
                description: 'The underwire in the BEAUTIFUL bra subtly lifts and centres the bust in a flattering, super sexy style. Classic modal and microfibre bra.',
                category: "Bras, classic",
                type: "Bras",
                price: "26.00"
            },
        ],
    },
    bras_pushup: {
        id: 1,
        title: "Pushup Bras",
        routeName: 'bras_pushup',
        items: [

        ]
    }
}