export const sliderActionTypes = {
    TOGGLE_SLIDER_BRAS: 'TOGGLE_SLIDER_BRAS',
    TOGGLE_SLIDER_PANTIES: 'TOGGLE_SLIDER_PANTIES',
    TOGGLE_SLIDER_ACCESSORIES: 'TOGGLE_SLIDER_ACCESSORIES',
    TOGGLE_SLIDER_SLEEPWEAR: 'TOGGLE_SLIDER_SLEEPWEAR'
}