export const sliderActionTypes = {
    TOGGLE_SLIDER_BRAS: 'TOGGLE_SLIDER_BRAS',
    TOGGLE_SLIDER_PANTIES: 'TOGGLE_SLIDER_PANTIES',
    TOGGLE_SLIDER_ACCESSORIES: 'TOGGLE_SLIDER_ACCESSORIES',
    TOGGLE_SLIDER_SLEEPWEAR: 'TOGGLE_SLIDER_SLEEPWEAR',
    TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
    DROP_ALL_SLIDERS: 'DROP_ALL_SLIDERS',
}