export const indiActionTypes = {
    TOGGLE_INDI_PAGE: 'TOGGLE_INDI_PAGE',
    SET_SINGLE_ITEM: 'SET_SINGLE_ITEM',
    EMPTY_SINGLE_ITEM: 'EMPTY_SINGLE_ITEM',
    PICK_SIZE: 'PICK_SIZE',
    PICK_CUP: 'PICK_CUP',
    CLEAR_PICKED_SIZES: 'CLEAR_PICKED_SIZES'
}