export const filtersActionTypes = {
    SET_FILTERED_ITEMS: 'SET_FILTERED_ITEMS',

    TOGGLE_COLOR_FILTER: 'TOGGLE_COLOR_FILTER',
    TOGGLE_SIZE_FILTER: 'TOGGLE_SIZE_FILTER',
    TOGGLE_CUP_FILTER: 'TOGGLE_CUP_FILTER',
    CLOSE_ALL_FILTERS: 'CLOSE_ALL_FILTERS',
    CLEAR_FILTERS_VALUES: 'CLEAR_FILTERS_VALUES',

    COLOR_TO_FILTER: 'COLOR_TO_FILTER',
    SIZE_TO_FILTER: 'SIZE_TO_FILTER',
    CUP_TO_FILTER: 'CUP_TO_FILTER',

    REMOVE_COLOR_FILTER: 'REMOVE_COLOR_FILTER',
    REMOVE_SIZE_FILTER: 'REMOVE_SIZE_FILTER',
    REMOVE_CUP_FILTER: 'REMOVE_CUP_FILTER',

    SET_GRID_SMALL: 'SET_GRID_SMALL',
    SET_GRID_NORMAL: 'SET_GRID_NORMAL'
}